cc_library(
    name = "layout",
    srcs = glob([
        "*.cpp"
    ]),
    hdrs = glob([
        "*.hpp"
    ]),
    linkopts = [
        "-lpthread"
    ],
    deps = [
        "//:ogdf"
    ],
    visibility = ["//visibility:public"],
)