cc_library(
    name = "parser",
    srcs = glob([
        "*.cpp"
    ]),
    hdrs = glob([
        "*.hpp"
    ]),
    deps = [
        "@onnx//:onnx"
    ],
    visibility = ["//visibility:public"],
)